### ISSUE TITLE
検索結果一覧のデザインを修正

### ISSUE THREAD

**Issue by wakamenori** [wakamenori/yuru-corpus-frontend#108]
問題点
- カードの高さが違いすぎる
- 検索キーワードが`text-overflow: ellipsis; `で非表示部分に含まれるケースがある
- 検索キーワードがどこに含まれているのかわかりにくい
- 登場した発話のみでは文脈を把握できない

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/98820865/210595516-05c77ad3-3f56-483f-9a50-6485fd0cd19b.png">

**Comment by sumsat** [comment]
フィルターが見えなくなるのも不便かもしれないです

**Comment by wakamenori** [comment]
@sumsat 検索結果にはまだフィルター導入してないです！
フィルター導入する際は、「検索結果:66件」のところをフィルターに置き換え、件数表示はフィルター内部に取り込む予定です。
